// Mock data based on the screenshot (Thorvald, Elara, Solana, Shade, Vael, Hinterland tavern)

window.MOCK = {
  session: {
    name: "First",
    phase: "exploration",
    round: 0,
    turn: 5,
    savedAt: "22/04/26 11:12",
  },

  narrativeLog: [
    {
      id: 1,
      type: "narration",
      speaker: "Maître du jeu",
      text: "« Parfait ! » répète le tavernier en frappant ses mains l'une contre l'autre avec satisfaction. Il fait signe à une serveuse aux joues roses qui s'empresse de guider le groupe vers une table spacieuse près de la cheminée, où les flammes dansent en projetant des ombres chaleureuses sur les murs de pierre. Le négoçit arrive bientôt dans de lourdes écuelles de terre cuite, fumant et parfumé. La viande fond sous la cuillère, imprégnée d'un bouillon riche où flottent carottes, navets et herbes aromatiques. Une miche de pain frais complète le repas, sa croûte dorée craquant sous les doigts. Autour de vous, la vie de l'auberge continue son cours. Un barde accorde son luth près du coin opposé, tandis que des marchands discutent de leurs routes commerciales à voix basse.",
    },
    {
      id: 2,
      type: "narration",
      speaker: "Maître du jeu",
      text: "Le tavernier, qui s'est présenté comme Bram, passe régulièrement pour s'assurer que tout convient. « Si vous cherchez des nouvelles de la région, n'hésitez pas à demander », murmure-t-il en remplissant vos chopes de bière ambrée. « Un voyageur comme vous entend toujours des choses intéressantes par ici. »",
    },
    {
      id: 3,
      type: "player",
      speaker: "Thorvald",
      text: "Justement, donnez nous des nouvelles de la région et nous pourrions peut etre vous rendre utile",
    },
    {
      id: 4,
      type: "narration",
      speaker: "Maître du jeu",
      text: "Bram s'essuie les mains sur son tablier taché, puis s'accoude discrètement contre le comptoir, baissant légèrement la voix comme pour partager un secret. « Les temps sont troublés dans le Hinterland, mes amis. Les fermiers de la vallée du Nord rapportent des disparitions — du bétail d'abord, puis des voyageurs sur la route de Pierrefort. Certains parlent d'ombres qui bougent la nuit, d'autres de gobelins plus audacieux qu'à l'habitude. » Le tavernier jette un coup d'œil autour de lui avant de poursuivre. « Le Capitaine Harlon de la Garde cherche des volontaires pour enquêter. Il offre cinquante pièces d'or pour quiconque ramènera des réponses — ou des têtes. »",
    },
    {
      id: 5,
      type: "narration",
      speaker: "Maître du jeu",
      text: "« Et puis il y a l'ancienne mine de cristal, à l'ouest. Fermée depuis qu'un éboulement a libéré… quelque chose. Un alchimiste de passage m'a dit avoir vu des lueurs étranges dans les profondeurs. » La harpe du barde résonne doucement, couvrant momentanément le murmure qui s'est installé à une table. Bram redresse sa stature imposante et reprend son ton habituel. « Mais tout ça attendra demain. Pour ce soir, mangez, buvez, et reposez-vous. Un aventurier bien reposé vaut deux guerriers fatigués, c'est ce que dit ma défunte femme. » Il leur adresse un clin d'œil avant de retourner servir d'autres clients.",
    },
    {
      id: 6,
      type: "system",
      text: "Phase : exploration",
    },
    {
      id: 7,
      type: "narration",
      speaker: "Maître du jeu",
      text: "Une lourde porte de chêne coulit vient de se refermer derrière les aventuriers, coupant la lumière du jour. Désormais, seul un mince filet de poussière dorée filtre à travers les fissures du plafond voûté, dansant lentement dans l'air stagnant. L'odeur de pierre humide et de mousse ancienne emplit les narines, mêlée à quelque chose de plus métallique — du sang séché, peut-être, ou la rouille de très vieilles chaînes. Le corridor s'étire devant eux, pavé de dalles inégales qui crissent sous les bottes. Des torches éteintes jalonnent les murs à intervalles réguliers, leurs supports de fer forgé rongés par le temps. Au loin, un goutte-à-goutte régulier résonne quelque part dans l'obscurité, comme un compte à rebours patient. Thorvald, Elara, Solana et Shade se tiennent au seuil de ce lieu oublié, leurs souffles forment de légers nuages pâles dans l'air froid. Devant eux, le passage se divise : à gauche, une pente descendante s'enfonce dans les ténèbres ; à droite, une arche effondrée laisse entrevoir une lueur bleutée, pulsante et étrange, qui semble provenir d'une salle plus vaste.",
    },
  ],

  characters: [
    {
      id: "thorvald",
      name: "Thorvald",
      class: "Barbare",
      species: "Nain des montagnes",
      level: 1,
      hp: 12,
      hpMax: 12,
      ai: false,
      ac: 14,
      scores: { FOR: 16, DEX: 13, CON: 15, INT: 8, SAG: 10, CHA: 10 },
    },
    {
      id: "elara",
      name: "Elara",
      class: "Rôdeuse",
      species: "Elfe",
      level: 1,
      hp: 7,
      hpMax: 7,
      ai: false,
      ac: 13,
      scores: { FOR: 11, DEX: 17, CON: 12, INT: 13, SAG: 15, CHA: 10 },
    },
    {
      id: "solana",
      name: "Solana",
      class: "Clerc",
      species: "Humaine",
      level: 1,
      hp: 10,
      hpMax: 10,
      ai: true,
      ac: 16,
      scores: { FOR: 12, DEX: 10, CON: 14, INT: 10, SAG: 16, CHA: 13 },
    },
    {
      id: "shade",
      name: "Shade",
      class: "Roublard",
      species: "Demi-elfe",
      level: 1,
      hp: 10,
      hpMax: 10,
      ai: true,
      ac: 14,
      scores: { FOR: 9, DEX: 17, CON: 12, INT: 14, SAG: 11, CHA: 13 },
    },
    {
      id: "vael",
      name: "Vael",
      class: "Ranger",
      species: "Elf",
      level: 1,
      hp: 11,
      hpMax: 11,
      ai: false,
      ac: 13,
      scores: { FOR: 10, DEX: 17, CON: 13, INT: 12, SAG: 14, CHA: 8 },
      active: true,
    },
  ],

  saves: [
    {
      id: "s1",
      name: "First",
      phase: "exploration",
      turn: "Tour 5",
      round: 0,
      date: "22/04/26 11:12",
    },
  ],
};
